# Generated by Django 2.0.5 on 2018-05-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Other', 'Other'), ('Rental', 'Rental'), ('School', 'School')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('rent', models.CharField(max_length=100)),
                ('bedrooms', models.CharField(max_length=2)),
                ('bathrooms', models.CharField(max_length=2)),
                ('link', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
