# Generated by Django 2.0.5 on 2018-05-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20180509_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('School', 'School'), ('Job', 'Job'), ('Other', 'Other')], max_length=10)),
                ('user', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
    ]
